'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("henna_hub_MS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16373_simplemehndidesignforlefthand_hennabymahiramohsin_loop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16373-simplemehndidesignforlefthand-hennabymahiramohsin-loop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16373_simplemehndidesignforlefthand_hennabymahiramohsin_loop1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16373-simplemehndidesignforlefthand-hennabymahiramohsin-loop1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _53af64188acd795233ffb557d84996f5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("53af64188acd795233ffb557d84996f5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6f25a8190362c8ad2d4f61b043822145() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6f25a8190362c8ad2d4f61b043822145", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8b428e2b357addbdf27423f99ba352d7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8b428e2b357addbdf27423f99ba352d7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _95776_simple_mehndi_designs_bliss_henna_by_zahra_minimal_mehndi_chains() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("95776-simple-mehndi-designs-bliss-henna-by-zahra-minimal-mehndi-chains", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arabic_mehndi_design_3_696x696() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arabic-mehndi-design-3-696x696", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arabic_mehndi_designs_henna_by_ibka_cuffs_and_statement_finger_rings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arabic-mehndi-designs-henna-by-ibka-cuffs-and-statement-finger-rings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property e82a28df4d3c17a22b76ac91f16eaeee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e82a28df4d3c17a22b76ac91f16eaeee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NinaMichael_1178() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NinaMichael-1178", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property O2P1BbFzr54sZc2HY__BsyroKiFGeUnL42oTG6xsqt0s_vTWWnDjDWdq_eRdNgsHDCfsBRvFVd4tPrccdHfNnOG_d2F95SCrF2EmetCN19iWRzr6qM8G_mLr1yid051FJlZI5clD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("O2P1BbFzr54sZc2HY--BsyroKiFGeUnL42oTG6xsqt0s-vTWWnDjDWdq_eRdNgsHDCfsBRvFVd4tPrccd"& _ 
                        "HfNnOG_d2F95SCrF2EmetCN19iWRzr6qM8G_mLr1yid051FJlZI5clD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OIP__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OIP (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property R1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property roomana1_768x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roomana1-768x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Simple_Indian_Mehendi_Design_for_Leg_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Simple-Indian-Mehendi-Design-for-Leg-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trailing_Finger_Mehndi_Design_819x1024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trailing-Finger-Mehndi-Design-819x1024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhatsApp_Image_2020_08_26_at_2_05_33_PM_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhatsApp-Image-2020-08-26-at-2.05.33-PM-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
